.MODEL SMALL
.STACK 100H
.DATA
MSG DB "BISMILLAHIR RAHMANIR RAHEEM"
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV CX,27
    MOV AH,2
    L:
    MOV DL,MSG[SI]
    INC SI
    INT 21H
    LOOP L
    MAIN ENDP
END MAIN